# Generated by Django 2.0.2 on 2018-02-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaraunts', '0003_restaraunt_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaraunt',
            name='closing',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='restaraunt',
            name='opening',
            field=models.TimeField(),
        ),
    ]
