# Generated by Django 2.0.2 on 2018-02-27 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaraunts', '0004_auto_20180219_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.IntegerField(max_length=6)),
                ('restaraunt', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaraunts.Restaraunt')),
            ],
        ),
    ]
